[package]
name = "godot-cell"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.1"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "ffi"]
categories = ["game-engines", "graphics"]

[features]
proptest = ["dep:proptest"]

[dependencies]
proptest = { version = "1.4.0", optional = true }
